# Generated by Django 3.0.4 on 2020-04-10 10:27

import accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_trader', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.CustomUser')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number entered was not correctly formated.', regex='^\\+?1?\\d{9,15}$')])),
                ('company', models.CharField(blank=True, max_length=30)),
                ('street_village', models.CharField(blank=True, max_length=254)),
                ('district', models.CharField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=254)),
                ('country', django_countries.fields.CountryField(blank=True, default='TZ', max_length=2)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to=accounts.models.profile_pic_filename, verbose_name='Profile Picture')),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.CustomUser')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number entered was not correctly formated.', regex='^\\+?1?\\d{9,15}$')])),
                ('street_village', models.CharField(blank=True, max_length=254)),
                ('district', models.CharField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=254)),
                ('country', django_countries.fields.CountryField(blank=True, default='TZ', max_length=2)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to=accounts.models.profile_pic_filename, verbose_name='Profile Picture')),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.CustomUser')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number entered was not correctly formated.', regex='^\\+?1?\\d{9,15}$')])),
                ('company', models.CharField(blank=True, max_length=30)),
                ('street_village', models.CharField(blank=True, max_length=254)),
                ('district', models.CharField(blank=True, max_length=254)),
                ('region', models.CharField(blank=True, max_length=254)),
                ('country', django_countries.fields.CountryField(blank=True, default='TZ', max_length=2)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to=accounts.models.profile_pic_filename, verbose_name='Profile Picture')),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
